Add converter for Arctica-M N1 RSR data.
pytroll/pyspectral pull request #145
Opened 2022-02-08 12:30 UTC by simonrp84

This adds spectral response functions for the MSU-GS/A instruments aboard the Arctica-M N1 satellite.
There are two instruments aboard the satellite, which have differing spectral response functions. Here I add them as `det-1` and `det-2`.

 - [ ] Tests passed: Passes ``pytest pyspectral``
 - [ ] Passes ``flake8 pyspectral`` 
 - [ ] Fully documented

2022-02-09 08:33 UTC, pnuu commented on pyspectral/utils.py
> +def convert2hdf5(ClassIn, platform_name, bandnames, scale=1e-06, dets=None):
I think the new kwarg should be `detectors` for clarity. And have a short explanation in the docstring.

2022-02-09 08:34 UTC, pnuu commented on rsr_convert_scripts/msu_gsa_reader.py
> +        tohdf5(MsugsaRSR, platform_name, MSUGSA_BAND_NAMES, dets=['det-1', 'det-2'])
And also remember to update the kwarg naming here.

2022-02-09 18:11 UTC, adybbroe commented
@simonrp84 You can update `utils.py` with this url and bump the version to 1.0.18:
`https://zenodo.org/record/6026563/files/pyspectral_rsr_data.tgz`

2022-02-10 09:58 UTC, simonrp84 commented
Thanks for the comments @pnuu and @adybbroe! I think I've updated / addressed everything now. I also added `Arctica-M-N1` to the `INSTRUMENTS` dict in `utils.py`.

2022-02-10 14:01 UTC, adybbroe commented on pyspectral/utils.py
> +HTTP_PYSPECTRAL_RSR = "https://zenodo.org/record/6026563/files/pyspectral_rsr_data.tg"
Should be `tgz` as file extension!

2022-02-10 14:13 UTC, adybbroe requested changes
Sorry @simonrp84 But could you please add some testing on your added code in `utils.py`? The coverage went down. I didn't pay attention to that previously....

2022-03-17 15:29 UTC, simonrp84 commented
> Sorry @simonrp84 But could you please add some testing on your added code in `utils.py`? The coverage went down. I didn't pay attention to that previously....
Looking at what's changed, it seems that the function I altered didn't have any tests before - so I would need to add them. This will probably not be a quick effort as I've not worked with mocking HDF5 before. Will see what I can do.

2022-09-28 14:11 UTC, adybbroe commented on pyspectral/utils.py
> +                grp.attrs['number_of_detectors'] = len(detectors)
This seems untested. Could we improve that?

2022-09-28 14:11 UTC, adybbroe commented on pyspectral/utils.py
> +                arr = sensor.rsr['wavelength']
Also here, this is not tested it seems.

2022-09-28 14:11 UTC, adybbroe commented on pyspectral/utils.py
> +                dset[...] = arr
Same here, is this tested?

2022-09-28 14:12 UTC, adybbroe commented on pyspectral/utils.py
> +                    dset[...] = arr
Again, not covered by tests I think.

2022-09-28 14:13 UTC, adybbroe reviewed
There are changes to utils.py which seems poorly covered by tests. Is it something you can try improve? Or do you need help?

2022-09-28 14:17 UTC, adybbroe commented
@simonrp84 I will try see if I can help our here. Maybe as Arctica-M is kind of on hold as we have no real-time flow of data this PR is not urgent and we can see if we find some time improving the test coverage of the `convert2hdf5` function before merging. Ok?

2022-09-29 08:06 UTC, simonrp84 commented
To be honest I've forgotten what I did in this PR! Will check through it next week and then we can figure out how to move on it. Like you say, no rush now.

2022-10-03 10:05 UTC, simonrp84 commented
I have now added some tests that should improve the coverage of the code previously missed. I chose to not mock the `h5py` library but to actually reader an HDF5 RSR file through the tests and then delete it after. Am unsure if this is the best way to do things so please let me know what you think!

2022-10-10 15:30 UTC, adybbroe approved these changes
LGTM

2022-10-10 18:50 UTC, merged