Add RSR reader for the EPIC instrument onboard DSCOVR
pytroll/pyspectral pull request #200
Opened 2023-10-18 10:56 UTC by simonrp84

This PR adds a conversion script for spectral response functions for the EPIC instrument aboard the DSCOVR satellite. 

It converts the excel file with RSR data into an HDF5 file suitable for pyspectral.

2023-10-20 11:52 UTC, adybbroe approved these changes
LGTM! Many thanks. Just one comment that I also want your view on?
Maybe @rolle-at-work , @mraspaud and others have an opinion as well here?

2023-10-20 11:52 UTC, adybbroe commented on rsr_convert_scripts/epic_reader.py
Looks fine. The only thing is that the responses are not normalized. I saw that from your HDF5 file you provided. However, right now I can't find another example where we actively normalize the responses if the originals were not. Most often they are. Also MetImage has non-normalized RSR at the moment. So we can leave this for another PR.

I generally think we should make sure all responses are normalized (to 1). It makes plotting various instrument RSRs on the same plot more convenient if nothing else.

2023-10-20 12:32 UTC, adybbroe requested changes
We need changing the name of the hdf5 file as said...
I am testing off line. Will come back

2023-10-20 13:16 UTC, rolle-at-work commented on rsr_convert_scripts/epic_reader.py
Finally managed to login here again...
Yes I had some problems before with non-normalized RSR's. So before I used an RSR I make sure it is normalized and in correct order. 
But it is a good thing to protect others from bad experience by normaliszing RSRs directly.

2023-10-20 13:33 UTC, simonrp84 commented
OK, have done all the above - should be better now :)

2023-10-20 13:33 UTC, simonrp84 commented on rsr_convert_scripts/epic_reader.py
Done!

2023-10-21 10:37 UTC, adybbroe commented on rsr_convert_scripts/epic_reader.py
Looks good, thanks!

2023-10-21 10:39 UTC, adybbroe approved these changes
LGTM. I have updated Zenodo and the link and version in Pyspectral. (Unfortunately forgot to state the right version (1.2.4) on Zenodo, so now it says version 30. But should not have any affect as long as the link in `utils.py` is correct.

2023-10-21 10:56 UTC, merged